### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by vangheem** [collective/collective.readonlymode#1]
There are already a package that might do what this is aiming: https://github.com/collective/wildcard.readonly

There is also https://github.com/collective/wildcard.lockdown which can be related.

**Comment by rafaelbco** [comment]
Thank you @vangheem! 

I knew about the first one. The second one actually can do what I want. You saved me some work!

**Comment by rafaelbco** [comment]
Since we are at it. I'd like to implement two new features on wildcard.lockdown:

1. View to enable/disable easily using cURL. My goal is use to use this in deploy automation.
2. Option to display a status message when read-only mode is enabled.

What do you think? May I start working on this on a branch?

**Comment by vangheem** [comment]
Have at it. I don't use the project anymore so any work on it would be welcome!

**Comment by gforcada** [comment]
I would use that as well, would you be interested in PLIPing it?

**Comment by rafaelbco** [comment]
I need to address an immediate need and time is short. 

Let me try to implement the 2 features in wildcard.lockdown for now and later we see about a PLIP, ok?

**Comment by gforcada** [comment]
Of course, no problem 😃
